apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggy-app
  labels:
    app: buggy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buggy-app
  template:
    metadata:
      labels:
        app: buggy-app
    spec:
      containers:
      - name: buggy-app
        image: buggy-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: buggy-app-svc
spec:
  selector:
    app: buggy-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000